### ISSUE TITLE
Render 3D Animation of time-evolving state function

### ISSUE THREAD

**Issue by jam31118** [jam31118/qprop#25]
# TODO
- [ ] Find proper threshold of data to be plotted
- [ ] Consider using color or opacity gradation indicating the function value
- [ ] Use #24 if available
